### ISSUE TITLE
[BUG] I can generate a wordlist with 0 word !

### ISSUE THREAD

**Issue by ReDiiX** [tatam/lama#17]
Hi,

Lama is cool, i can generate my wordlist only with the -h or the -y (or both) option. 

> root@debian:# lama 1 2 /tmp/test.lst -h > wordlist/plante.lst
> lama
> will generate 0 words.     (~0o)
> Do you want to process ? [y/N] y
> Generation... Done

Regards,
Aurélien

**Comment by tatam** [comment]
Hi !

Thanks for your return !

This issue was fixed. Now lama want a display option or not running:

> root@debian-ml:lama# lama 1 4 example/alice.lst -hy > /tmp/dico
> lama: No display options specified.
> [...]

Regards,
Tatam.
