### ISSUE TITLE
comparison between pointer and zero character constant

### ISSUE THREAD

**Issue by LucasGaleano** [tatam/lama#22]
https://github.com/tatam/lama/blob/b106d6c6d68272e0a3ff9bbcfc86f76973c9af45/src/lama_split.c#L82

should compare the value "if ( * words[0] != '\0')", because it does not compile in linux mint :)
or use strcmp() instead.

**Comment by tatam** [comment]
Thanks a lot for the feedback !

It's corrected. can you tell me if it's ok for you on Linux Mint ?

Tatam.

**Comment by tatam** [comment]
I close this issue.

Let me know if you have already this bug.

Tatam
